name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests-apigee:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
            node-version: "18"
      - name: Install latest uuid npm
        run: |
          npm install uuid@7.0.3 -g
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run POSTMAN collection for Apigee
        run: |
         newman run ./Mock/Mock_Test_Suite.postman_collection.json -e ./Mock/Test_Mock.postman_environment.json --reporter-htmlextra-export mock_result.html --verbose  
